name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_SSH_LARAVEL_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_LARAVEL_USERNAME }}
          password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
          script: |
            echo "Contents of /var/www/html:"
            ls -l /var/www/html
            echo "Running deploy script..."
            cd /var/www/html
            ./deploy.sh
