name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader
          npm install
          npm run build

      - name: Deploy to VPS
        run: |
          ssh ${{ secrets.HOSTINGER_SSH_LARAVEL_USER }} << 'EOF'
            cd /htdocs/srv590533.hstgr.cloud
            git pull origin master
            composer update
            composer install --no-dev --prefer-dist --optimize-autoloader
            npm install
            npm run build
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
